### ISSUE TITLE
Need Help with CDF

### ISSUE THREAD

**Issue by arilwan** [AllenDowney/empiricaldist#19]
HI @AllenDowney,
I have been trying to use CDF plot for a multiclass  dataframe, but all efforts failed. Here's how my dataframe looks like:
```
data.shape
(4672, 6)

data.head()
+---+---------+----------+----------+-------+--------------+------------+
|   | trip_id | duration | distance | speed | acceleration | travelmode |
+---+---------+----------+----------+-------+--------------+------------+
| 0 |  303633 |     2657 | 5624.06  | 2.12  | 0.00080      | bus        |
| 1 |  303637 |     1185 | 1274.04  | 1.08  | 0.00091      | foot       |
| 2 |  303638 |     1185 | 4464.56  | 3.77  | 0.00318      | car        |
| 3 |  303642 |     3350 | 7715.78  | 2.30  | 0.00069      | bus        |
| 4 |  303657 |      704 | 1155.26  | 1.64  | 0.00233      | car        |
+---+---------+----------+----------+-------+--------------+------------+
```

Now I want 4 CDF plots each for duration, distance, speed, and acceleration for the 5-class `travelmode` in the dataset `[bike, bus, car, foot, metro]`. I have been trying this for two days, but mess-up.

My objective is to plot (for each of duration, speed, distance, acc.) a distribution by mode, something like the following:
![Screenshot 2019-11-04 at 22 43 34](https://user-images.githubusercontent.com/42409395/68164543-fb4d6580-ff54-11e9-800c-ab13a3570841.png)

Any help please?

**Comment by AllenDowney** [comment]
If you can send me starter code, I might be able to work up an example.

But I would start with

```
for name, group in data.groupby('travelmode'):
 Cdf.from_seq(group.duration).plot()
```

On Mon, Nov 4, 2019, at 5:47 PM, Akilu Rilwan Muhammad wrote:

> HI @AllenDowney <https://github.com/AllenDowney>,
>  I have been trying to use CDF plot for a multiclass dataframe, but all efforts failed. Here's how my dataframe looks like:

> `data.shape
(4672, 6)

data.head()
+---+---------+----------+----------+-------+--------------+------------+
|   | trip_id | duration | distance | speed | acceleration | travelmode |
+---+---------+----------+----------+-------+--------------+------------+
| 0 |  303633 |     2657 | 5624.06  | 2.12  | 0.00080      | bus        |
| 1 |  303637 |     1185 | 1274.04  | 1.08  | 0.00091      | foot       |
| 2 |  303638 |     1185 | 4464.56  | 3.77  | 0.00318      | car        |
| 3 |  303642 |     3350 | 7715.78  | 2.30  | 0.00069      | bus        |
| 4 |  303657 |      704 | 1155.26  | 1.64  | 0.00233      | car        |
+---+---------+----------+----------+-------+--------------+------------+
`

**Comment by arilwan** [comment]
Yes, I share below, my notebook (code) and the sample dataset.

[mode_cdf.ipynb.zip](https://github.com/AllenDowney/empiricaldist/files/3806558/mode_cdf.ipynb.zip)
[april2016.csv.zip](https://github.com/AllenDowney/empiricaldist/files/3806562/april2016.csv.zip)

**Comment by AllenDowney** [comment]
Does that mean you figured it out? If so, well done!

**Comment by arilwan** [comment]
Yes, many thanks.

**Comment by arilwan** [comment]
I'm very sorry to reopen this issue, I'm  in need of help with the plot, I couldn't manage **to add a label** to the plot to show which plot is for which mode?
```
for name, group in data1.groupby('travelmode'):
    Cdf.from_seq(group.speed).plot()
    

title, x, y = 'Speed by mode','speed (km/h)', 'CDF'

decorate_cdf(title,x,y)
```
![Screenshot from 2019-12-02 10-47-16](https://user-images.githubusercontent.com/42409395/69953460-3067bc00-14f1-11ea-83a3-39d0ce4d46d3.png)

**Comment by AllenDowney** [comment]
When you call `plot` on a `Cdf`, you can calling plot on a Pandas series. It takes the same keyword arguments, including `label`.

**Comment by arilwan** [comment]
Oh yes, adding
`plt.legend(data.groupby('travelmode').groups.keys())`
to my `decorate_cdf` function did the trick.
