### ISSUE TITLE
Typo in anaconda package name

### ISSUE THREAD

**Issue by MikolajKolman** [AllenDowney/empiricaldist#20]
I've tried downloading the package using anaconda and noticed there is a typo in the name. 

https://anaconda.org/conda-forge/empyrical-dist

It's still the same package from what I have seen inside it, but it might cause errors. In my case it was when I've run utils.py in the notebook from the third chapter of Think Bayes. The workaround is obviously to install the package using pip, but I wanted to put this out there.

**Comment by jdblischak** [comment]
The package was renamed to empiricaldist. We recently created a new conda package with the new name. You can install it from the conda-forge channel:

```
conda install -c conda-forge empiricaldist
```

https://anaconda.org/conda-forge/empiricaldist
https://github.com/conda-forge/empiricaldist-feedstock

**Comment by AllenDowney** [comment]
Thank you both!
