### ISSUE TITLE
License mismatch?

### ISSUE THREAD

**Issue by hyandell** [AllenDowney/empiricaldist#22]
Hi Allen,

The overall package is BSD-3-Clause, but the test file is under GPL-3.0. I could see that being intentional, only at test time is the whole GPL-3.0; but as it can cause confusion and might be accidental, I thought I would point it out and see if it's intended to be BSD-3-Clause instead.

**Comment by hyandell** [comment]
While I'm at it; also noting that https://github.com/AllenDowney/empiricaldist/blob/master/empiricaldist/empiricaldist.py is MIT rather than BSD-3-Clause.

**Comment by jdblischak** [comment]
@hyandell Thanks for pointing this out. This was fixed in PR #21. The entire repo is now consistently licensed as BSD-3-Clause

**Comment by AllenDowney** [comment]
Thank you both!
