### ISSUE TITLE
Installing empiricaldist on a mac

### ISSUE THREAD

**Issue by paulathomas** [AllenDowney/empiricaldist#31]
I am trying to install empiricaldist on a mac with python 3.11. Python changed the way it installs packages at 3.10(?). Anyway certainly 3.11 uses macos's frameworks technology. So when I try to install empiricalldist on my mac it goes into the local site-packages for python 3.9 instead of the framework for 3.11.

Is there any way I could use scipy's binomial pmf as a workaround?

**Comment by paulathomas** [comment]
Now solved ! completely removed empiricaldist and pip then reinstalled both.

**Comment by AllenDowney** [comment]
Glad you got it working!
